#-------------------------------
# General Site Settings

title: Siddharth
logo: 
author: themefisher
description: this is meta description
email: SiddharthJSingh@protonmail.com
phone: +91 9000968078
address: C/O Jagpal Singh, Near E.S.I Office, 4th Cross Road, Junglighat, Port Blair-744103, India
copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
- {name: Home, link: '#'}
- {name: About, link: '#about'}
- {name: Blog, link: '#blog'}
- {name: Portfolio, link: '#portfolio'}
- {name: Contact, link: '#contact'}


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

google-analytics: G-MM2F5FN4DZ


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Hero Section

hero:
  hero-title: Hi! I’m <br> Siddharth J Singh <br> C++ Developer <br> !!Site under construction!!

social:
- {icon: "ti-facebook", link: "#"}
- {icon: "ti-instagram", link: "#"}
- {icon: "ti-dribbble", link: "#"}
- {icon: "ti-twitter", link: "#"}


#-------------------------------
# About (Section and Page)

# About Section
blurb:
  I am a passionate programmer who has been in the industry for about five years now. I left the industry briefly to pursue a Master's program. I took up pragmatic and diverse courses/projects like Image Processing, Deep Learning, Robotics, Computer Vision, Computational Photography, and Computer Graphics.<br><br> I am an individual contributor at present, but I am looking for more challenging and mentoring roles as the next step in my career. I am an expert Linux user, and I have invested primarily in the C++ programming language because of the domains it is applied in. Game Development is one such domain, and it has always intrigued me since childhood. I've done some independent work to prove my motivation, and I am currently looking for a job in the Game Development industry. I think my skillsets and interests align with the industry, and this is where I want to be.

#-------------------------------
# Skills Section

skills-title: Skills
skills:
- {name: Web Design, color: '#fdb157', value: '90%'}
- {name: Logo Design, color: '#9473e6', value: '60%'}
- {name: After Effects, color: '#bdecf6', value: '80%'}
- {name: Web App, color: '#ffbcaa', value: '70%'}



#-------------------------------
# Timeline Section

timeline-title: Timeline
timeline:
- {name: Bachelor of Technology, 
   date: 'July 2008- June 2012',
   organization: 'National Institute of Technology, Warangal',
   type: 'ed'
  }
- {name: Software Engineer, 
   icon: 'icon-2.png', 
   date: 'June 2012 - Oct 2015', 
   organization: 'CA Technologies',
   type: 'work'
  }
- {name: Master of Science(By Research), 
   date: 'July 2016 - June 2019', 
   organization: 'Indian Institute of Technology, Kanpur',
   type: 'ed'
  }
- {name: Software Engineer, 
   icon: 'icon-3.png', 
   date: 'July 2019 - Present', 
   organization: 'Mathworks',
   type: 'work'
  }


#-------------------------------
# Blog (Section and Page)

# Blog Home Section
blog-home-items:
  - image : "assets/images/portfolio/bullet-physics.png"
    url: "/blog/non_intrusive_visitor"

  - image : "assets/images/portfolio/true-dice.png"
    url: "/blog/non_intrusive_visitor"

#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image : "assets/images/portfolio/bullet-physics.png"
    url: "/pf/bullet-physics"

  - image : "assets/images/portfolio/true-dice.png"
    url: "/pf/true-dice"
    
#-------------------------------
# Testimonials Section
# TODO: Ask collegues to give this information and add

testimonial-items:
  - name: "Jesica Gomez"
    image: "assets/images/testimonial/client-1.png"
    designation : "CEO, Funder"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
    
  - name: "Jesica Gomez"
    image: "assets/images/testimonial/client-1.png"
    designation: "CEO, Funder"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
    
  - name: "Jesica Gomez"
    image: "assets/images/testimonial/client-1.png"
    designation: "CEO, Funder"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."


#-------------------------------
# Client Slider Section

client-slider-items:
  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"

#-------------------------------
# Contact Section

contact-title: Contact Me
formspree-endpoint: f/xeqpyeoa
