#-------------------------------
# General Site Settings

title: Siddharth
logo: 
author: themefisher
description: this is meta description
email: SiddharthJSingh@protonmail.com
phone: +91 9000968078
address: C/O Jagpal Singh, Near E.S.I Office, 4th Cross Road, Junglighat, Port Blair-744103, India
copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
- {name: Home, link: '#'}
- {name: About, link: '#about'}
- {name: Blog, link: '#blog'}
- {name: Portfolio, link: '#portfolio'}
- {name: Contact, link: '#contact'}

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

google-analytics: G-MM2F5FN4DZ

#-------------------------------
# Comment Section (Disqus)
disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Hero Section

hero:
  hero-title: Hi! I’m <br> Siddharth J Singh <br> C++ Developer <br> !!Site under construction!!

social:
- {icon: "ti-facebook", link: "#"}
- {icon: "ti-instagram", link: "#"}
- {icon: "ti-dribbble", link: "#"}
- {icon: "ti-twitter", link: "#"}

#-------------------------------
# About (Section and Page)

# About Section
blurb:
  I am a passionate programmer who has been in the industry for about five years now. I left the industry briefly to pursue a Master's program. I took up pragmatic and diverse courses/projects like Image Processing, Deep Learning, Robotics, Computer Vision, Computational Photography, and Computer Graphics.<br><br> I am an individual contributor at present, but I am looking for more challenging and mentoring roles as the next step in my career. I am an expert Linux user, and I have invested primarily in the C++ programming language because of the domains it is applied in. Game Development is one such domain, and it has always intrigued me since childhood. I've done some independent work to prove my motivation, and I am currently looking for a job in the Game Development industry. I think my skillsets and interests align with the industry, and this is where I want to be.

#-------------------------------
# Skills Section

skills-title: Skills
skills:
- {name: Web Design, color: '#fdb157', value: '90%'}
- {name: Logo Design, color: '#9473e6', value: '60%'}
- {name: After Effects, color: '#bdecf6', value: '80%'}
- {name: Web App, color: '#ffbcaa', value: '70%'}

#-------------------------------
# Timeline Section

timeline-title: Timeline
timeline:
  -
    date: "July 2008- June 2012"
    items:
      -
        text: "Obtained A+ grades in Data structures and Algorithmsi."
      -
        text: "Gained 3rd position in Game Design competition."
      -
        text: "Underwent training program at BSNL."
    name: "Bachelor of Technology"
    organization: "National Institute of Technology, Warangal"
    type: ed
  -
    date: "June 2012 - Oct 2015"
    items:
      -
        text: "Worked on an Enterprise Storage Management software, CA SRM."
      -
        text: "Roles included system administration for storage hardware, writing automation testbeds."
      -
        text: "Was part of an Event Management Team to handle and coordinate Team outings. Eventually led the team briefly."
      -
        text: "Completed OCA, Java SE 7 Certification."
      -
        text: "Switched internally to work with CA SiteMinder, an enterprise Security and SSO solution."
      -
        text: "Learnt software debugging and various technologies as LDAP, Kerberos, REST. Fixed low priority bugs."
    name: "Software Engineer"
    organization: "CA(India) Technologies Pvt. Ltd."
    type: 'work'
  -
    date: "July 2016 - June 2019"
    items:
      -
        text: "Cleared GATE with a rank of 802, 99.99% numer of candidates."
      -
        text: "Coursework: Probabilistic Mobile Robotics, Signal Processing, Image Processing, Mathematical methods and Modelling"
      -
        text: "Joined Team IITK-TCS for Amazon Robotics Challenge 2017. Roles included programming low and high level image processing, networking, load balancing and reducing latency. Won 3rd, 4th and 5th prizes in the event which took place in Robocup 2017, Nagoya, Japan. Add video below"
      -
        text: "Worked on extracting depth information from Light-field data using a simulated annealing algorithm."
      -
        text: "Used Light-field digital refocussing algorithm to patent a novel orthographic imaging algorithm."
      -
        text: "Developed a portable version of a device capable of counting 200 micron steel sheets with an accuracy of 99.6%."
      -
        text: "Developed physical hardware for a Light-Field capture system for capturing images across a plane."
      -
        text: "Demonstrated the generalized abilty of orthographic capture using the patented algorithm to count straws(simulating hard to move steel rebars)."
    name: "Master of Science(By Research)"
    organization: "Indian Institute of Technology, Kanpur"
    type: ed
  -
    date: "July 2019 - Present"
    items:
      -
        text: "Provided Technical Support to customers by direct engagement which helped in understanding requirements."
      -
        text: "Working on Embedded Coder Toolbox for Simulink, used to generate C/C++ code from graphical models."
      -
        text: "I own the parameter binding phase of the in-house compiler, fixing bugs in this module and increase the scope for correct code generation."
      -
        text: "Improved the code generation infrastructure by modelling Simulink semantics better in the intermediate representation."
      -
        text: "The work improved code robustness and preemptively handled customer bugs."
      -
        text: "It also enhanced code quality, such as const qualifying read-only parameters."
      -
        text: "Continuing my efforts for better and correct representation of Simulink semantics for backend code generation."
    name: "Software Engineer"
    organization: "MathWorks India Pvt. Ltd."
    type: work

#-------------------------------
# Blog (Section and Page)

# Blog Home Section
blog-home-items:
  - image : "assets/images/blog/visitor.jpg"
    url: "/blog/non_intrusive_visitor"

  - image : "assets/images/blog/fsm.png"
    url: "/blog/state_pattern"

#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image : "assets/images/portfolio/bullet-physics.png"
    url: "/pf/bullet-physics"

  - image : "assets/images/portfolio/true-dice.png"
    url: "/pf/true-dice"
    
#-------------------------------
# Testimonials Section
# TODO: Ask collegues to give this information and add

testimonial-items:
  - name: "Jesica Gomez"
    image: "assets/images/testimonial/client-1.png"
    designation : "CEO, Funder"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
    
  - name: "Jesica Gomez"
    image: "assets/images/testimonial/client-1.png"
    designation: "CEO, Funder"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
    
  - name: "Jesica Gomez"
    image: "assets/images/testimonial/client-1.png"
    designation: "CEO, Funder"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."


#-------------------------------
# Client Slider Section

client-slider-items:
  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"

#-------------------------------
# Contact Section

contact-title: Contact Me
formspree-endpoint: f/xeqpyeoa
